### PR TITLE
Adding hex translation to messages

### PR DESCRIPTION
**Pull request by WuzzyLV**
#### `STATS_STATS: '&#4287f5&l%PLAYER%''s Statistics'`
Alt text

#### `GUI_SELECTION: '&#9965a1CoinFlipper Selection'`
Alt text

### CODE REVIEW

**Comment by WuzzyLV** [comment]
@gronnmann :)

**Comment by gronnmann** [comment]
Sorry, completely forgot about it. Will look tjrough tomorrow!

**Comment by WuzzyLV** [comment]
Just merge big man

**Comment by WuzzyLV** [comment]
Im using my fork to yeet the legacy code and make the plugin overall more usable, so gonna close this.

**Pull request closed without merging**
